export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  sepoliaRpcUrl: process.env.SEPOLIA_RPC_URL ?? "",
  sepoliaRelayerPrivateKey: process.env.SEPOLIA_RELAYER_PRIVATE_KEY ?? "",
  creditcoinRpcUrl: process.env.CREDITCOIN_RPC_URL ?? "",
  creditcoinRelayerPrivateKey: process.env.CREDITCOIN_RELAYER_PRIVATE_KEY ?? "",
  sourceBatchRegistryAddress: process.env.SOURCE_BATCH_REGISTRY_ADDRESS ?? "",
  settlementContractAddress: process.env.SETTLEMENT_CONTRACT_ADDRESS ?? "",
  batchSettlementAddress: process.env.BATCH_SETTLEMENT_ADDRESS ?? "",
  attestcoinChainKey: process.env.ATTESTCOIN_CHAIN_KEY ?? "",
  attestcoinProofServiceUrl: process.env.ATTESTCOIN_PROOF_SERVICE_URL ?? "",
  sourceBatchRegistryDeployBlock: process.env.SOURCE_BATCH_REGISTRY_DEPLOY_BLOCK ?? "",
  settlementDeployBlock: process.env.SETTLEMENT_DEPLOY_BLOCK ?? "",
  batchSettlementDeployBlock: process.env.BATCH_SETTLEMENT_DEPLOY_BLOCK ?? "",
  /** Previous source registries still worth reading: "address:deployBlock,address:deployBlock". */
  retiredRegistries: process.env.RETIRED_REGISTRIES ?? "",
};
